#version 430 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(std430, binding = 0) readonly buffer CurrentGrid
{
    uint currentGrid[];
};

layout(std430, binding = 1) writeonly buffer NextGrid
{
    uint nextGrid[];
};

uniform int width;
uniform int height;

void main()
{
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;

    //clamp within grid
    if (x >= uint(width) || y >= uint(height))
        return;

    int liveCount = 0;

    //check neighbors
    for (int offsetY = -1; offsetY <= 1; offsetY++)
    {
        for (int offsetX = -1; offsetX <= 1; offsetX++)
        {
            //dont count curr cell
            if (offsetX == 0 && offsetY == 0)
                continue;

            int nx = int(x) + offsetX;
            int ny = int(y) + offsetY;

            //wrap over edge x
            if (nx < 0)
                nx = width - 1;
            else if (nx >= width)
                nx = 0;

            //wrap over edge y
            if (ny < 0)
                ny = height - 1;
            else if (ny >= height)
                ny = 0;

            uint neighborIndex = uint(nx + ny * width);

            liveCount += int(currentGrid[neighborIndex]);
        }
    }

    uint index = y * uint(width) + x;

    uint currentCell = currentGrid[index];

    //cgol rules
    if (currentCell == 1)
    {
        if (liveCount == 2 || liveCount == 3)
            nextGrid[index] = 1;
        else
            nextGrid[index] = 0;
    }
    else
    {
        if (liveCount == 3)
            nextGrid[index] = 1;
        else
            nextGrid[index] = 0;
    }
}